sudo: false
language: java
install: /bin/true
script:
 - mvn -f modules/swagger-parser-v2-converter validate -D copy-dependencies
 - mvn verify
jdk:
  - oraclejdk8
after_success:
  - if [ $SONATYPE_USERNAME ] && [ -z $TRAVIS_TAG ] && [ $TRAVIS_PULL_REQUEST == false ]; then
      mvn clean deploy --settings .travis/settings.xml;
    fi;
